#!/bin/bash

IP=$(ifconfig  | grep inet | awk 'NR==1' | awk '{print $2;}')
WIRED=$(nmcli connection show --active | grep -e 'enp3s0')

if [ ! $WIRED ] 
then
    echo "  127.0.0.1"
else [ $WIRED ] 
    echo "  $IP"
separator_block_width=3
fi

case $BLOCK_BUTTON in
	1) gnome-terminal -e nmtui ;;
esac
