#!/bin/bash
IP=$(ifconfig | grep -e "broadcast" | awk 'NR==1' | awk '{print $2;}')

if [ $IP ]
then
    echo "  $IP"
else 
    echo "  127.0.0.1"
fi

case $BLOCK_BUTTON in
	1) gnome-terminal -e nmtui ;;
esac
