#!/bin/bash

if [ $(pulsemixer --get-mute) -eq 1 ]
    then echo "婢 MUTE"
else
  echo " $(pulsemixer --get-volume | awk '{print $1}')%"
fi

case $BLOCK_BUTTON in
	1) ( pavucontrol & ) && disown;;
	3) pulsemixer --toggle-mute ;;  # right click, mute/unmute
	4) pulsemixer --change-volume +5 ;; # scroll up, increase
	5) pulsemixer --change-volume -5 ;; # scroll down, decrease
esac
