#!/bin/bash

SSID=$(nmcli device | awk 'NR==2' | awk '{print $4;}')
ENABLED=$(nmcli radio wifi | grep enabled)
CONNECTED=$(nmcli connection show --active | grep wlp2s0)

if [ $ENABLED ]
then
    if [ $SSID = "BCPublic" ]
    then
        echo   @$SSID
    elif [ $CONNECTED ]
    then
        STRENGTH=$(nmcli device wifi | grep $SSID | awk '{print $7;}')
        echo    $STRENGTH% @$SSID
    else
        echo "   No Wifi"
    fi
else [ ! $ENABLED ]
    echo "  Airpane Mode"
    separator_block_width=3
fi

case $BLOCK_BUTTON in
	1) gnome-terminal -e nmtui ;;
	2) sh ~/dotfiles/scripts/i3blocks/toggle_wifi.sh ;;
    3) nm-applet ;;
esac
